jobs:
  build-and-maybe-push:
    runs-on: [docker]

    container:
      image: node:20-alpine
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Instalar Docker CLI dentro do container
        run: |
          apk add --no-cache docker-cli
        shell: sh

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set DO_PUSH flag (push só na branch main)
        id: setflag
        run: |
          if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "do_push=true" >> $GITHUB_OUTPUT
          else
            echo "do_push=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$TAG .
        shell: sh

      - name: Login in registry
        if: steps.setflag.outputs.do_push == 'true'
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login localhost:3000 -u "${{ secrets.REGISTRY_USER }}" --password-stdin
        shell: sh

      - name: Push image
        if: steps.setflag.outputs.do_push == 'true'
        run: |
          docker push $IMAGE_NAME:$TAG
        shell: sh
