name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]

env:
  # CORRIGIDO: Removido o "http://"
  REGISTRY: server:3000
  IMAGE_NAME: forgejo/aplicacao-rust
  
  # A tag completa está correta
  IMAGE_TAG: server:3000/forgejo/aplicacao-rust:latest

jobs:
  build-and-push:
    runs-on: docker

    steps:
      - name: Checkout code (Manual)
        run: |
            echo "Cleaning workspace..."
            find . -mindepth 1 -delete

            echo "Cloning repository..."
            git config --global http.extraHeader "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
            git clone --depth=1 --branch ${{ github.ref_name }} ${{ github.server_url }}/${{ github.repository }} .
            git config --global --unset http.extraHeader
        shell: sh

      - name: Login to Forgejo Registry
        run: |
          # CORRIGIDO: Usando env.REGISTRY em vez de variables.REGISTRY_SERVER_URL
          echo "Logging into ${{ env.REGISTRY }}..."
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login http://${{ env.REGISTRY }} -u "${{ secrets.REGISTRY_USER }}" --password-stdin
        shell: sh

      - name: Build Docker image
        run: |
          echo "Building image ${{ env.IMAGE_TAG }}..."
          docker build -t ${{ env.IMAGE_TAG }} -f ./Dockerfile .
        shell: sh

      - name: Push image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Pushing image ${{ env.IMAGE_TAG }}..."
          docker push ${{ env.IMAGE_TAG }}
        shell: sh
