name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]

env:
  # ⚠️ ATENÇÃO: Corrigido de 'localhost' para 'server'.
  # 'localhost' não funciona de dentro do container do job.
  REGISTRY: server:3000
  IMAGE_NAME: forgejo/aplicacao-rust
  
  # Criamos uma tag completa para facilitar
  IMAGE_TAG: server:3000/forgejo/aplicacao-rust:latest

jobs:
  build-and-push:
    runs-on: docker
    
    steps:
      - name: Checkout code
        # Mantemos esta, pois é a forma padrão de obter o código
        uses: actions/checkout@v4

      - name: Login to Forgejo Registry
        # Substitui a 'docker/login-action'
        run: |
          echo "Logging into ${{ env.REGISTRY }}..."
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u "${{ secrets.REGISTRY_USER }}" --password-stdin
        shell: sh

      - name: Build Docker image
        # Substitui a 'docker/build-push-action' (parte de build)
        # Removemos o 'setup-buildx' e usamos o build padrão
        run: |
          echo "Building image ${{ env.IMAGE_TAG }}..."
          docker build -t ${{ env.IMAGE_TAG }} -f ./Dockerfile .
        shell: sh

      - name: Push image
        # Substitui a 'docker/build-push-action' (parte de push)
        # A lógica 'if' garante que o push só ocorre no branch 'main'
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Pushing image ${{ env.IMAGE_TAG }}..."
          docker push ${{ env.IMAGE_TAG }}
        shell: sh