name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: https://github.com/actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t aplicacao-rust:latest .
          docker tag aplicacao-rust:latest aplicacao-rust:$GITHUB_SHA

      - name: Login to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin ${{ github.server_url }}

      - name: Tag and push image
        run: |
          SERVER=$(echo "${{ github.server_url }}" | sed 's|https://||' | sed 's|http://||')
          IMAGE="${SERVER}/${{ github.repository_owner }}/aplicacao-rust"

          docker tag aplicacao-rust:latest ${IMAGE}:latest
          docker push ${IMAGE}:latest

          echo "Image pushed: ${IMAGE}:latest"
