name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]

env:
  # Use o registry do seu Forgejo. Geralmente é o próprio domínio.
  REGISTRY: localhost:3000
  IMAGE_NAME: forgejo/aplicacao-rust # O registry será prefixado automaticamente

jobs:
  build-and-push:
    runs-on: docker # ou o label do seu runner com Docker instalad
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Forgejo Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile # Opcional, se o nome for Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest # Monta a tag completa
          cache-from: type=gha
          cache-to: type=gha,mode=max