name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]

# O bloco 'env' foi movido 

jobs:
  build-and-push:
    runs-on: docker

    steps:
      - name: Checkout code (Manual)
        run: |
            echo "Cleaning workspace..."

            echo "Cloning repository..."
            git config --global http.extraHeader "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
            git clone --depth=1 --branch ${{ github.ref_name }} ${{ github.server_url }}/${{ github.repository }} .
            git config --global --unset http.extraHeader
        shell: sh

      - name: Login no Docker Hub (Manual)
        run: |
          echo "Logando no Docker Hub..."
          # Este é o comando shell equivalente ao 'docker/login-action'
          echo dckr_pat_16ur0fiCce7pGosFUVoQuoIYicY | docker login -u viniciusbonatti --password-stdin

      - name: Construir e publicar a imagem (Manual)
        run: |
          DOCKER_IMAGE="viniciusbonatti/aplicacao-rust:latest"
          echo $DOCKER_IMAGE
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE