name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*"

env:
  IMAGE_NAME: aplicacao-rust

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker --version

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.IMAGE_NAME }}:latest

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin ${{ github.server_url }}

      - name: Push Docker image
        if: github.event_name != 'pull_request'
        run: |
          REGISTRY_URL=$(echo "${{ github.server_url }}" | sed 's|https://||' | sed 's|http://||')
          FULL_IMAGE_NAME="${REGISTRY_URL}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}"

          docker tag ${{ env.IMAGE_NAME }}:latest ${FULL_IMAGE_NAME}:latest
          docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${FULL_IMAGE_NAME}:${{ github.sha }}

          docker push ${FULL_IMAGE_NAME}:latest
          docker push ${FULL_IMAGE_NAME}:${{ github.sha }}

          echo "✅ Imagem publicada: ${FULL_IMAGE_NAME}:latest"
