name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]

# O bloco 'env' foi movido daqui...

jobs:
  build-and-push:
    runs-on: forgejo-runner

    # ...para dentro do job, para que possamos usar 'variables
    env:
      IMAGE_NAME: forgejo/aplicacao-rust
      # A tag agora é construída usando a variável do UI
      IMAGE_TAG: ${{ variables.REGISTRY_SERVER_URL }}/${{ env.IMAGE_NAME }}:latest

    steps:
      - name: Checkout code (Manual)
        run: |
            echo "Cleaning workspace..."

            echo "Cloning repository..."
            git config --global http.extraHeader "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
            git clone --depth=1 --branch ${{ github.ref_name }} ${{ github.server_url }}/${{ github.repository }} .
            git config --global --unset http.extraHeader
        shell: sh

      - name: Login to Forgejo Registry
        run: |
          # Restaurado conforme sua solicitação
          echo "Logging into ${{ variables.REGISTRY_SERVER_URL }}..."
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ variables.REGISTRY_SERVER_URL }} -u "${{ secrets.REGISTRY_USER }}" --password-stdin
        shell: sh

      - name: Build Docker image
        run: |
          # Esta etapa agora usa a IMAGE_TAG construída com sua variável
          echo "Building image ${{ env.IMAGE_TAG }}..."
          docker build -t ${{ env.IMAGE_TAG }} -f ./Dockerfile .
        shell: sh

      - name: Push image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Pushing image ${{ env.IMAGE_TAG }}..."
          docker push ${{ env.IMAGE_TAG }}
        shell: sh

