name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: forgejo.seudominio.com/seu-usuario/sua-imagem # TODO ajustar
  TAG: latest # ou usa SHA, versão etc.

jobs:
  build-and-maybe-push:
    runs-on: [docker]
    steps:
      - name: Checkout code
        run: |
          git clone ${{ github.server_url }}/${{ github.repository }} .
          git checkout ${{ github.sha }}
        shell: bash

      - name: Set DO_PUSH flag (push só na branch main)
        id: setflag
        run: |
          if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "do_push=true" >> $GITHUB_OUTPUT
          else
            echo "do_push=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$TAG .
        shell: bash

      - name: Login in registry
        if: steps.setflag.outputs.do_push == 'true'
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login localhost:3000 -u "${{ secrets.REGISTRY_USER }}" --password-stdin
        shell: bash

      - name: Push image
        if: steps.setflag.outputs.do_push == 'true'
        run: |
          docker push $IMAGE_NAME:$TAG
        shell: bash
