name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: registry.seudominio.com/seu-usuario/sua-imagem  # ajuste pro seu registry
  TAG_SHA: ${{ github.sha }}
  TAG_LATEST: latest

jobs:
  build-and-maybe-push:
    runs-on: [docker]

    container:
      image: docker:27-git

    steps:
      - name: Checkout code
        shell: bash
        run: |
          git clone ${{ github.server_url }}/${{ github.repository }} .
          git checkout ${{ github.sha }}

      - name: Set DO_PUSH flag (push só na branch main)
        id: setflag
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "do_push=true" >> $GITHUB_OUTPUT
          else
            echo "do_push=false" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker image
        shell: bash
        run: |
          docker build -t $IMAGE_NAME:$TAG_SHA -t $IMAGE_NAME:$TAG_LATEST .

      - name: Login in registry
        if: steps.setflag.outputs.do_push == 'true'
        shell: bash
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" \
          | docker login registry.seudominio.com -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Push image
        if: steps.setflag.outputs.do_push == 'true'
        shell: bash
        run: |
          docker push $IMAGE_NAME:$TAG_SHA
          docker push $IMAGE_NAME:$TAG_LATEST
